### ISSUE TITLE
answers to 3 and 8 are wrong too

### ISSUE THREAD

**Issue by maymayw** [HeroKillerEver/coursera-deep-learning#2]
3: does not need bh and bw
8: 1/9

**Comment by HeroKillerEver** [comment]
Can u be more specific?

**Comment by ekrismer** [comment]
The answers in "Convolutional Neural Networks/week3 quiz.md" should be updated as stated above.

**Comment by HeroKillerEver** [comment]
Thanks for @epicStudio and @maymayw. I will update accordingly.
