### ISSUE TITLE
Wrong Answer on CNN Week 2 Quiz

### ISSUE THREAD

**Issue by sherwinfarrell** [HeroKillerEver/coursera-deep-learning#8]
The answer to the 8th question seems to be wrong. 

Suppose you have an input volume of dimension nH x nW x nC. Which of the following statements you agree with? (Assume that “1x1 convolutional layer” below always uses a stride of 1 and no padding.)

You can use a 1x1 convolutional layer to reduce nC but not nH, nW.

You can use a 1x1 convolutional layer to reduce nH, nW, and nC.

You can use a pooling layer to reduce nH, nW, but not nC.

You can use a pooling layer to reduce nH, nW, and nC.

The second option regarding pooling layers has been highlighted with the wrong answer:
 It should be: You can use a pooling layer to reduce nH, nW, but not nC.
and not: You can use a pooling layer to reduce nH, nW, and nC.

**Comment by VismayTandel** [comment]
Write answer is You can use a 1x1 convolutional layer to reduce nC but not nH, nW.
The explanation is that there is written that stride of 1 and no padding so if you use a formula to calculate nH and nW it is same as previous
nC[l] =( (nC[l-1]+2*padding-f)/2 ) + 1

**Comment by sherwinfarrell** [comment]
What you are talking about is the first answer, I presume. There are in fact 2 answers to this question.
I see a problem with the second answer over here. To make it slightly more clear I feel the answers should be:
1. You can use a 1x1 convolutional layer to reduce nC but not nH, nW.
2. You can use a pooling layer to reduce nH, nW, but not nC.

**Comment by HeroKillerEver** [comment]
Thanks for the detailed discussion, I have updated the answer.

**Comment by anishchhaparwal** [comment]
> Thanks for the detailed discussion, I have updated the answer.

i cannot see your answer. what is the solution to the question?
